### PR TITLE
Allow user to specify seed for RNG

### PR DESCRIPTION
**Pull request by jstjohn**
This is an untested change to allow the end-user to specify the seed for the RNG used by preseq. Do you have any tests that you typically run the various code through to verify correctness? It would be great to have a `make test` type rule at some point. Thanks!

### CODE REVIEW

**Comment by jstjohn** [comment]
We did some light testing insofar as we have verified that the results look similar between this and the master branch version, and the results do not appear to change between runs if you specify the `-seed INT` argument.

**Comment by andrewdavidsmith** [comment]
I'll try to look at this soon. Thanks!!!

Sent from my iPhone

On Sep 14, 2016, at 9:49 AM, John St. John <notifications@github.com<mailto:notifications@github.com>> wrote:


We did some light testing insofar as we have verified that the results look similar between this and the master branch version, and the results do not appear to change between runs if you specify the -seed INT argument.

-

**Comment by nboley** [comment]
Any update on this?

**Comment by timydaley** [comment]
I updated preseq with a rng seed option that I had written in as part of https://github.com/timydaley/preseq_dev.  
Thank you for the reminder, this had completely slipped my mind.

**Comment by nboley** [comment]
Hi Tim, thanks for looking at this. 
One question: 
If I understand the commit correctly, setting the seed to 0 with the command line option would actually result in a random seed being chosen. I think that this behavior is a bit unexpected -- the original PR got around this by initializing the seed to random and then allowing optparse to override this. 

Do I understand correctly?

Thank you!

**Comment by timydaley** [comment]
Yeah.  I could instead set it to max int initially.  Very few people would choose that random seed.


Timothy Daley

Stanford University, Departments of Statistics and Bioengineering.

________________________________

**Comment by jstjohn** [comment]
What's wrong with setting it to a random seed always, then letting the user
override that? Fewer lines of code.

**Comment by timydaley** [comment]
Nothing.  I just had this already written, it's already put in everything, and I already tested it.  So it was fewer lines for me to write and that point in time.


Timothy Daley

Stanford University, Departments of Statistics and Bioengineering.

________________________________

**Comment by nboley** [comment]
Thanks for doing this! Do you have any idea when this will be merged into master?

Best, Nathan

**Comment by andrewdavidsmith** [comment]
If this isn't resolved, please open an issue. It easy to add a desired default initial behavior for setting a seed. I think it's pretty good how it is, and likely not the way it was 5 years ago at the time of this discussion.

**Pull request closed without merging**
